### ISSUE TITLE
Cannot open Kanban Board in Markdown mode

### ISSUE THREAD

**Issue by ghost** [valentine195/obsidian-markdown-attributes#17]
**Describe the bug**
While the markdown attribute plugin is activated there is no possibility to open a Kanban Board in markdown mode. Once I deactivate the markdown attribute plugin, I can do so without any problem

**Screenshots**

![errormessage](https://user-images.githubusercontent.com/61102969/212264106-ed8410ef-083b-474c-b486-484eb94161db.jpg)

**Comment by sigrunixia** [comment]
With Markdown-Attributes + Kanban Enabled:

```js
 case 5:
                            return n = o.sent(),
                            this.file = null,
                            new EP('Failed to load "'.concat(e.path, '". ').concat(n.message)),
                            console.error(n),
                            [3, 6];


Exception: Failed to execute 'setAttribute' on 'Element': '"kanban-plugin":"basic"' is not a valid attribute name.
    at t.setAttrs (app://obsidian.md/app.js:1:371351)
    at t.sync (app://obsidian.md/app.js:1:371601)
    at e.sync (app://obsidian.md/app.js:1:364021)
    at t.sync (app://obsidian.md/app.js:1:385927)
    at e.sync (app://obsidian.md/app.js:1:364021)
    at app://obsidian.md/app.js:1:405181
    at e.ignore (app://obsidian.md/app.js:1:478543)
    at t.updateInner (app://obsidian.md/app.js:1:404977)
    at new t (app://obsidian.md/app.js:1:403178)
    at e.setState (app://obsidian.md/app.js:1:488033)
(anonymous) @ app.js:1
```

Without it, Kanban loads just fine. Is this an our plugin issue, @valentine195

**Comment by ksdavidc** [comment]
This is still happening and has not been "completed"
