### ISSUE TITLE
Using numbers in curly braces in mermaid diagrams, and maybe code blocks cause file to fail to open

### ISSUE THREAD

**Issue by ksdavidc** [valentine195/obsidian-markdown-attributes#18]
**Describe the bug**
Using numbers in curly braces in mermaid diagrams, and maybe code blocks cause file to fail to open

**Markdown Source**
The markdown source that caused the rendering issue.
````
```mermaid 
flowchart TD
q1{no text 1}
id2((round))
D[do this instead]
A-->q1-->|YES| id3[text]
q1-->|no|D-->id2
```
````

renders the following message in the console

```
(anonymous) @ app.js:1
app.js:1 DOMException: Failed to execute 'setAttribute' on 'Element': '1' is not a valid attribute name.
    at t.setAttrs (app://obsidian.md/app.js:1:328808)
    at t.sync (app://obsidian.md/app.js:1:329056)
    at t.e.sync (app://obsidian.md/app.js:1:321690)
    at t.sync (app://obsidian.md/app.js:1:329126)
    at t.e.sync (app://obsidian.md/app.js:1:321690)
    at t.sync (app://obsidian.md/app.js:1:342464)
    at t.e.sync (app://obsidian.md/app.js:1:321690)
    at app://obsidian.md/app.js:1:361236
    at e.ignore (app://obsidian.md/app.js:1:431021)
    at t.updateInner (app://obsidian.md/app.js:1:361032)
(anonymous) @ app.js:1

```

sometimes even just plain code blocks do the same

````
```
test{with number 1}
```
````

slightly tempermental bug. Things work for a while (minutes?), but then reverts.

**Screenshots**
<img width="2048" alt="Screen Shot 2023-01-31 at 5 50 05 AM" src="https://user-images.githubusercontent.com/62230004/215592051-51db002a-3060-4147-84f5-65fd08ab42a4.png">

**Comment by sigrunixia** [comment]
Confirmed this is still an issue. Markdown-attributes appears very sensitive to `word{ }` and `word { }` combinations.
